### ISSUE TITLE
Mapeamento Frete Pela Frenet

### ISSUE THREAD

**Issue by ricardopantani** [eloom/module-bling-nfe#1]
Estou tendo problemas para configurar o mapeamento de frete pela Frenet. 

![image](https://user-images.githubusercontent.com/45405370/201374789-b216fc0d-1cbd-4e26-9e4b-ec4bc69212dd.png)

![image](https://user-images.githubusercontent.com/45405370/201375062-783365aa-26e9-401d-887b-acc19ec54865.png)

Por favor, alguem poderia me ajudar nesse mapeamento?

**Comment by ricardopantani** [comment]
No campo "shipping_method" da tabela "sales_order" está : frenetshipping_03220   frenetshipping_F_3   frenetshipping_03298 frenetshipping_042 de alguns pedidos.
E para a escolha do método de envio só tem : [frenetshipping] frenet

**Comment by eloom** [comment]
O que ocorre é que o método de frete não está **desagrupando** os serviços. Há duas formas para contornar:

1 - você modificar o comportamento do módulo de frete e desagrupar os serviços, como a maioria faz. Pode ver um exemplo aqui https://github.com/eloom/module-correios-frete/blob/main/src/module-correios-frete/Model/Carrier.php, no método "getAllowedMethods()";

2 - modificar o comportamento do módulo Bling e comentar onde ocorre o erro, mas ao fazer isso, terá de preencher todos os dados de endereço e etiqueta de forma manual no Bling.
